name: "mixmaster-dev"
services:
  mixmaster-db:
    image: "mysql:latest"
    container_name: database
    restart: no
    environment:
      MYSQL_USER: mixmaster
      MYSQL_PASSWORD: mixmaster
      MYSQL_DATABASE: mixmaster
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mixapinetwork

  mixmaster-api:
    depends_on:
      - mixmaster-db
    image: "ghcr.io/mixmaster-app/mixapi:latest"
    container_name: mixapi
    restart: no
    ports:
      - 3000:3000
    volumes:
      - api_config:/var/app/config
    networks:
      - mixapinetwork

volumes:

  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

  api_config:
    driver: local
    driver_opts:
      type: none
      device: ../../app/src/main/resources
      o: bind

networks:
  mixapinetwork: