# Main
spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:mysql://127.0.0.1:33061/mixmaster?serverTimezone=UTC
    username: mixmaster
    password: mixmaster
  jpa:
    open-in-view: true
    hibernate.ddl-auto: update # none / validate / update / create-drop
  data:
    rest:
      detection-strategy: annotated
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS

# Default API config
server:
  port: 3000
  address: 0.0.0.0
  servlet:
    context-path: /api

# Swagger
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger.json

# Custom
mixapi:
  web-user-agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
  mixmaster:
    base-path: mixmaster-online.fr