# Main
spring:
  application:
    name: mixapi
  jmx:
    enabled: true
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:mysql://127.0.0.1:3306/mixmaster?serverTimezone=UTC
    username: mixmaster
    password: mixmaster
  jpa:
    hibernate.ddl-auto: validate # none / validate / update / create-drop
  data:
    rest:
      detection-strategy: annotated
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS

# Default API config
server:
  port: 3000
  address: 0.0.0.0
  servlet:
    context-path: /api

# Swagger
springdoc:
  swagger-ui:
    path: /swagger
  api-docs:
    path: /swagger.json

# Metrics
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      base-path: /metrics
      exposure:
        include: '*'
        exclude: beans
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    links:
      github: https://github.com/mixmaster-app/mixapi